### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by Derek-Cruz** [Derek-Cruz/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Movement function

- [x] Keydown space event 

- [x] Add setInterval every 16ms

- [x] Test and fix any errors
