### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by Derek-Cruz** [Derek-Cruz/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add Property to data for stop and go  

- [x] See if property is true or false

- [x] clear interval 

- [x] test and fix errors
