### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by Derek-Cruz** [Derek-Cruz/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Add property for steering to data model

- [x] update movement function for keydown 

- [x] check for unnecessary styling 

- [x] test and fix errors
